export { default as OrderMenuPage } from './OrderMenuPage/OrderMenuPage'
export { default as LoginPage } from './LoginPage/LoginPage'
export { default as RegisterPage } from './RegisterPage/RegisterPage'
export { default as LandingPage } from './LandingPage/LandingPage'
export { default as TablePage } from './TablePage/TablePage'